name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때마다 워크플로우 실행

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create config.js with API Key
      run: |
        echo "const UNSPLASH_ACCESS_KEY = '${{ secrets.UNSPLASH_ACCESS_KEY }}';" > config.js
      env:
        UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}

    - name: Build and prepare for deployment
      run: |
        mkdir build
        shopt -s extglob # 확장 글로빙 활성화
        cp -r !(build) build/ # 'build' 디렉토리를 제외한 모든 파일/디렉토리 복사
        # .DS_Store, .gitignore 등 숨김 파일도 복사 (필요한 경우)
        cp .DS_Store build/ 2>/dev/null || true
        cp .gitignore build/ 2>/dev/null || true

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './build' # build 디렉토리를 아티팩트로 업로드

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4